//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace COD03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public string Id { get; set; }
        public string name { get; set; }
        public Nullable<int> basesalary { get; set; }
        public Nullable<int> bonus { get; set; }
        public Nullable<int> deduct { get; set; }
        public Nullable<int> subtotal { get; set; }
        public Nullable<bool> status { get; set; }
        public string photo { get; set; }
    }
}
